### ISSUE TITLE
Segfault during async

### ISSUE THREAD

**Issue by rikvanderkemp** [spatie/async#115]
I have a very simple pool and async structure in symfony command:

```php
$pool = Pool::create();
$responses = [];

foreach ($include as $process) {
   $cmd = $this->getCommand($process); // returns an invocable class
   $pool[] = async(function () use ($cmd, $process, $directory) {
       $executed = new \DateTime();
       $result = $cmd($directory);
   
       return [$cmd->commandLine, $executed, $result];
    })->then(function ($action) use ($process, &$responses) {
        $this->dispatcher->logToConsole($action[0], $action[1]);
        $responses[$process] = $action[2];
    })->catch(function (\Exception $e) {
        dd($e);
    });;
}

$pool->wait();
```

This works as expected on my local machine.

<details>
<summary>Local specs</summary>

```
PHP 7.4.3 (cli) (built: May 26 2020 12:24:22) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
```

</details>

However, running the same script on the server, it immediately returns a Segfault.

<details>
<summary>Server specs</summary>

```
PHP 7.4.6 (cli) (built: May 14 2020 10:03:28) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.6, Copyright (c), by Zend Technologies
    with blackfire v1.34.3~linux-x64-non_zts74, https://blackfire.io, by Blackfire
```

</details>

So I tried to find the root of this using gdb, but couldn't debug.

Backtrace:
```
#0  0x00005555557cdb56 in _emalloc_56 ()
#1  0x00005555557ffd09 in _zend_new_array_0 ()
#2  0x000055555580cd12 in zend_fetch_debug_backtrace ()
#3  0x00005555558135db in ?? ()
#4  0x00005555557f6140 in object_init_ex ()
#5  0x0000555555858973 in ?? ()
#6  0x0000555555872708 in execute_ex ()
#7  0x0000555555879773 in execute_ex ()
#8  0x0000555555879773 in execute_ex ()
#9  0x0000555555878597 in execute_ex ()
#10 0x0000555555878597 in execute_ex ()
#11 0x00005555557e5b86 in zend_call_function ()
#12 0x00005555557e5d85 in _call_user_function_ex ()
#13 0x00005555556ceeb8 in ?? ()
#14 0x00005555556cef3b in ?? ()
#15 0x0000555555834eef in ?? ()
#16 0x0000555555871d98 in execute_ex ()
#17 0x000055555585b4ec in ?? ()
#18 0x000055555587245f in execute_ex ()
#19 0x00005555557e5b86 in zend_call_function ()
#20 0x00005555556ef48c in ?? ()
#21 0x00007ffff15c3fdd in bf_zend_execute_internal () from /usr/lib/php/20190902/blackfire.so
#22 0x00005555557e5caa in zend_call_function ()
#23 0x00005555557e605d in zend_lookup_class_ex ()
#24 0x00005555557e68dc in zend_fetch_class_by_name ()
#25 0x0000555555858607 in ?? ()
#26 0x00005555558733fa in execute_ex ()
#27 0x0000555555879773 in execute_ex ()
#28 0x0000555555879773 in execute_ex ()
#29 0x0000555555879773 in execute_ex ()
#30 0x0000555555879773 in execute_ex ()
#31 0x0000555555878597 in execute_ex ()
#32 0x000055555587a981 in zend_execute ()
#33 0x00005555557f43e3 in zend_execute_scripts ()
#34 0x0000555555793ba0 in php_execute_script ()
#35 0x000055555587ca96 in ?? ()
#36 0x000055555565b99b in ?? ()
#37 0x00007ffff743609b in __libc_start_main (main=0x55555565b550, argc=4, argv=0x7fffffffe3f8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffe3e8) at ../csu/libc-start.c:308
#38 0x000055555565bafa in _start ()
```
Thought I'd simplify the code back to it's bare form:

```php
$pool[] = async(function () {
                return '12345';
})->then(function ($action) use (&$responses) {
    $responses[] = $action;
})->catch(function (\Exception $e) {
    dd($e);
});
```

Now I get either a SegFault or, I get a ParallelError with code `0` and no message.

For the life of me I can't figure out why even the simplest form won't work. Btw, I also tried disabling Blackfire.

**Comment by brendt** [comment]
I'm afraid I won't be able to help with segfaults, it goes a little beyond my knowledge. The only thing I can think of is to try the same come on a VM of some sorts?
