### ISSUE TITLE
call_user_func() expects parameter 1 to be a valid callback, no array or string given

### ISSUE THREAD

**Issue by valh1996** [spatie/async#116]
Hello,

I get the following error, even with the simplest example:
```
[2020-06-18 17:15:16] development.ERROR: [18-Jun-2020 17:15:16 Europe/Zurich] PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, no array or string given in /var/www/html/vendor/spatie/async/src/Runtime/ChildRuntime.php on line 26
 {"exception":"[object] (Spatie\\Async\\Output\\ParallelError(code: 0): [18-Jun-2020 17:15:16 Europe/Zurich] PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, no array or string given in /var/www/html/vendor/spatie/async/src/Runtime/ChildRuntime.php on line 26
 at /var/www/html/vendor/spatie/async/src/Output/ParallelError.php:11)
[stacktrace]
#0 /var/www/html/vendor/spatie/async/src/Process/ParallelProcess.php(126): Spatie\\Async\\Output\\ParallelError::fromException('[18-Jun-2020 17...')
#1 /var/www/html/vendor/spatie/async/src/Process/ProcessCallbacks.php(54): Spatie\\Async\\Process\\ParallelProcess->resolveErrorOutput()
#2 /var/www/html/vendor/spatie/async/src/Process/ProcessCallbacks.php(38): Spatie\\Async\\Process\\ParallelProcess->triggerError()
#3 /var/www/html/vendor/spatie/async/src/Pool.php(182): Spatie\\Async\\Process\\ParallelProcess->triggerSuccess()
#4 /var/www/html/vendor/spatie/async/src/Pool.php(295): Spatie\\Async\\Pool->markAsFinished(Object(Spatie\\Async\\Process\\ParallelProcess))
#5 /var/www/html/vendor/spatie/async/src/Pool.php(131): Spatie\\Async\\Pool->Spatie\\Async\\{closure}(17, Array)
#6 /var/www/html/vendor/spatie/async/src/helpers.php(22): Spatie\\Async\\Pool->wait()
#7 /var/www/html/app/Console/Commands/test.php(62): await(Object(Spatie\\Async\\Pool))
#8 [internal function]: App\\Console\\Commands\\test->handle()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call(Array)
#15 /var/www/html/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#17 /var/www/html/vendor/symfony/console/Application.php(1011): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /var/www/html/vendor/symfony/console/Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\test), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /var/www/html/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
```

Here is my code:
```php
$pool = Pool::create();
$pool[] = async(new MyTask())->then(function (int $output) {
    echo $output;
});
await($pool);
```
```php
class MyTask extends Task
{
    public function configure()
    {
        //
    }

    public function run()
    {
        return 1;
    }
}
```

Extension pcntl is installed:
```
$:/var/www/html# php -i | grep pcntl
pcntl
pcntl support => enabled
PHP_DEFAULT_EXTENSIONS => mcrypt mysqli pdo_mysql intl sockets gmp opcache igbinary pcntl bcmath imagick
$_SERVER['PHP_DEFAULT_EXTENSIONS'] => mcrypt mysqli pdo_mysql intl sockets gmp opcache igbinary pcntl bcmath imagick
$_ENV['PHP_DEFAULT_EXTENSIONS'] => mcrypt mysqli pdo_mysql intl sockets gmp opcache igbinary pcntl bcmath imagick
```

Do you have any idea please??

Best regards,
Val

**Comment by brendt** [comment]
Hi Val, honestly no idea; your code works just fine when I tested it. Maybe you could try to clone this repo and run the testsuite on the same machine, are all tests green?

**Comment by valh1996** [comment]
I finally created a completely separate file for the task with only one class in it and it works.

**Comment by 73five** [comment]
I have the same error

**Comment by balabalab** [comment]
> 我终于为任务创建了一个完全独立的文件，其中只有一个类，并且它可以工作。

thanks.......two hours

**Comment by stz184** [comment]
This is the proper way to create tasks:

1. Create a folder holding the tasks, for example `/tasks`
2. Update your composer.json so it can autoload tasks from your `tasks` folder and run `composer update`
Example:
```
{
    "require": {
        "spatie/async": "^1.5"
    },
    "autoload": {
        "psr-4": {
            "tasks\\": "tasks/"
        }
    }
}
```
3. Set the proper path to your autoloader script so the async processes can benefit from it:
```
$pool = Pool::create()->autoload(__DIR__ . '/vendor/autoload.php');
```
5. Add your tasks to the pool as usual, i.e. `$pool->add(new MyTask());`
6. Voila! No more errors!
