### ISSUE TITLE
Parallel error using Task class

### ISSUE THREAD

**Issue by frufin** [spatie/async#146]
Hi, I get an error while using a very basic task :

```
Spatie\Async\Output\ParallelError in /srv/data/web/vhosts/www.mydomain.com/htdocs/staging/vendor/spatie/async/src/Output/ParallelError.php:11
Stack trace:
#0 /srv/data/web/vhosts/www.mydomain.com/htdocs/staging/vendor/spatie/async/src/Process/ParallelProcess.php(126): Spatie\Async\Output\ParallelError::fromException()
#1 /srv/data/web/vhosts/www.mydomain.com/htdocs/staging/vendor/spatie/async/src/Process/ProcessCallbacks.php(54): Spatie\Async\Process\ParallelProcess->resolveErrorOutput()
#2 /srv/data/web/vhosts/www.mydomain.com/htdocs/staging/vendor/spatie/async/src/Pool.php(232): Spatie\Async\Process\ParallelProcess->triggerError()
#3 /srv/data/web/vhosts/www.mydomain.com/htdocs/staging/vendor/spatie/async/src/Pool.php(328): Spatie\Async\Pool->markAsFailed()
#4 /srv/data/web/vhosts/www.mydomain.com/htdocs/staging/vendor/spatie/async/src/Pool.php(154): Spatie\Async\Pool->Spatie\Async\{closure}()
#5 /srv/data/web/vhosts/www.mydomain.com/htdocs/staging/php/divalto_updates/async.php(64): Spatie\Async\Pool->wait()
#6 {main}Spatie\Async\Output\ParallelError in /srv/data/web/vhosts/www.mydomain.com/htdocs/staging/vendor/spatie/async/src/Output/ParallelError.php:11
... (same error for any array element)
```
Here is my Task definition :
```
use Spatie\Async\Task; 
class updateTask extends Task
{
	private $table;
	
	public function __construct($t) {
		$this->table = $t;
	}
	public function configure(){
		return;
	}
	public function run(){
		print_r($this->table);
	}
}
```

And the script using that class :

```
$table_info = [...];
$pool = Pool::create();
foreach ($table_info as $t) {
	$task = new updateTask($t);
	$pool->add($task)
	->catch(function ($exception) {
		print($exception);
	});
}
$pool->wait();
```
This error only occurs on a server with pcntl and posix enabled.
On my dev server without pcntl enabled, everything works, synchronously of course. 

Thanks for your help !

**Comment by Bileslaw** [comment]
Hello, @frufin! Don't you figure out what the problem was? I think I faced the same issue. Here's mine: https://github.com/spatie/async/issues/151

**Comment by frufin** [comment]
Hi @Bileslaw, unfortunately, i can't help you ...
I got no answer from spatie (**still maintained ?**)
Anyway, i moved to a node.js server as javascript is natively asynchronous, and so nice to code.
I'm giving up PHP progressively but surely
Best !
