### ISSUE TITLE
No hope to have it working with symfony/process ^3.3 ?

### ISSUE THREAD

**Issue by DODMax** [spatie/async#28]
This way it would be compatible with Laravel.

**Comment by brendt** [comment]
Done! https://github.com/spatie/async/commit/b603dbae1eb8ce4255b755a9e0f686f5b9bd5233

Thanks for pointing this out. Note that there isn't a stable release yet, but this commit is tagged with 0.0.3: https://github.com/spatie/async/releases/tag/0.0.3

**Comment by DODMax** [comment]
Nice thanks, I created a Task as below and it works like a charm:

```php
namespace App\Libraries;
use Illuminate\Support\Facades\Hash;
use Illuminate\Contracts\Console\Kernel;
use Spatie\Async\Task;

class MyTask extends Task
{
    private $app;

    public function configure()
    {
        $this->app = require __DIR__.'/../../bootstrap/app.php';
        $this->app->make(Kernel::class)->bootstrap();
        Hash::setRounds(4);
    }

    public function execute()
    {
        $this->app->someLaravelLove();
    }
}
```

**Comment by andreshg112** [comment]
Hi @DODMax ! I don't understand how would I use facades inside the execute method.

https://github.com/spatie/async/issues/77:
I noticed that the Dijkstra instance is not serializable. So I decided to instantiate it inside the callback. The error is different now.

Code:
```php
$pool = Pool::create()
            ->autoload(__DIR__ . '/../../../vendor/autoload.php');

        // $i = 1;

        foreach (range(1, 5) as $i) {
            $pool[] = async(function () use ($i) {
                // Something to execute in a child process.
                $dijkstra = Edge::getDijkstra();
                return $i;
            })->then(function (int $output) {
                echo "{$output}<br>";
            })->catch(function (\Exception $exception) {
                // Handle exceptions thrown in the child process.
                throw $exception;
            });
        }

        await($pool);

        exit;
```

log:
```
[2019-07-04 17:11:01] local.ERROR: A facade root has not been set.

#0 /var/www/app/Edge.php(284): Illuminate\Support\Facades\Facade::__callStatic('rememberForever', Array)
#1 /var/www/app/Edge.php(255): App\Edge::getGraph()
#2 closure://function () use ($i) {
                // Something to execute in a child process.
                $dijkstra = \App\Edge::getDijkstra();
                return $i;
            }(4): App\Edge::getDijkstra()
#3 /var/www/vendor/spatie/async/src/Runtime/ChildRuntime.php(25): Opis\Closure\SerializableClosure->{closure}()
#4 {main} {"exception":"[object] (RuntimeException(code: 0): A facade root has not been set.

#0 /var/www/app/Edge.php(284): Illuminate\\Support\\Facades\\Facade::__callStatic('rememberForever', Array)
#1 /var/www/app/Edge.php(255): App\\Edge::getGraph()
#2 closure://function () use ($i) {
                // Something to execute in a child process.
                $dijkstra = \\App\\Edge::getDijkstra();
                return $i;
            }(4): App\\Edge::getDijkstra()
#3 /var/www/vendor/spatie/async/src/Runtime/ChildRuntime.php(25): Opis\\Closure\\SerializableClosure->{closure}()
#4 {main} at /var/www/vendor/spatie/async/src/Output/SerializableException.php:28)
[stacktrace]
#0 /var/www/vendor/spatie/async/src/Process/ParallelProcess.php(122): Spatie\\Async\\Output\\SerializableException->asThrowable()
#1 /var/www/vendor/spatie/async/src/Process/ProcessCallbacks.php(54): Spatie\\Async\\Process\\ParallelProcess->resolveErrorOutput()
#2 /var/www/vendor/spatie/async/src/Pool.php(203): Spatie\\Async\\Process\\ParallelProcess->triggerError()
#3 /var/www/vendor/spatie/async/src/Pool.php(299): Spatie\\Async\\Pool->markAsFailed(Object(Spatie\\Async\\Process\\ParallelProcess))
#4 /var/www/vendor/spatie/async/src/Pool.php(130): Spatie\\Async\\Pool->Spatie\\Async\\{closure}(17, Array)
#5 /var/www/vendor/spatie/async/src/helpers.php(22): Spatie\\Async\\Pool->wait()
#6 /var/www/app/Http/Controllers/NewPathController.php(66): await(Object(Spatie\\Async\\Pool))
#7 [internal function]: App\\Http\\Controllers\\NewPathController->__invoke(Object(App\\Http\\Requests\\PathRequest))
#8 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#9 /var/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('__invoke', Array)
#10 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\NewPathController), '__invoke')
#11 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#12 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(665): Illuminate\\Routing\\Route->run()
#13 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#14 /var/www/vendor/barryvdh/laravel-cors/src/HandleCors.php(36): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#15 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Barryvdh\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#22 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(642): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#23 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(608): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#24 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(597): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#25 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#26 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#40 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /var/www/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(29): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#43 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Barryvdh\\Cors\\HandlePreflight->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#46 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#47 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#48 /var/www/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#49 {main}
"} 
```
