### ISSUE TITLE
Fatal error:  Uncaught Spatie\Async\Output\ParallelError

### ISSUE THREAD

**Issue by JamesJGoodwin** [spatie/async#41]
Hello. I'm trying to run my code asynchronously, but I'm recieving an unknown error. Could you please take a look into it?

My environment: ubuntu 16.04, PHP 7.2.7 with PHP-FPM.

My code:
```
$pool = Pool::create();

$pool->add(function() {
    error_log('Async snapshot called');
    $html = getSnapshotHTML($full_uri);
    $source_code = pg_escape_string($html['source_code']);
    $url_path = parse_url($full_uri, PHP_URL_PATH);

    if($html['status_code'] == 200) {
        $query = "UPDATE snapshots SET (html, inserted) = ('$source_code', '$now') WHERE pathname = '{$url_path}'";
        $result = pg_query($query) or die('Query failed: ' . pg_last_error());   
    }
});
```

Stack trace:
```
2018/07/03 21:53:07 [error] 22566#22566: *2 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Spatie\Async\Output\ParallelError in /var/www/production/engine/vendor/spatie/async/src/Output/ParallelError.php:11
Stack trace:
#0 /var/www/production/engine/vendor/spatie/async/src/Process/ParallelProcess.php(126): Spatie\Async\Output\ParallelError::fromException('')
#1 /var/www/production/engine/vendor/spatie/async/src/Process/ProcessCallbacks.php(51): Spatie\Async\Process\ParallelProcess->resolveErrorOutput()
#2 /var/www/production/engine/vendor/spatie/async/src/Pool.php(197): Spatie\Async\Process\ParallelProcess->triggerError()
#3 /var/www/production/engine/vendor/spatie/async/src/Pool.php(285): Spatie\Async\Pool->markAsFailed(Object(Spatie\Async\Process\ParallelProcess))
#4 /var/www/production/engine/vendor/symfony/process/Process.php(830): Spatie\Async\Pool->Spatie\Async\{closure}(17, Array)
#5 /var/www/production/engine/vendor/symfony/process/Process.php(168): Symfony\Component\Process\Process->stop(0)
#6 [internal function]: Symfony\Component\Process\Proces" while reading upstream
```

**Comment by brendt** [comment]
You can catch the exception to debug it:

```php
$pool->add(function() {
    error_log('Async snapshot called');
    $html = getSnapshotHTML($full_uri);
    $source_code = pg_escape_string($html['source_code']);
    $url_path = parse_url($full_uri, PHP_URL_PATH);

    if($html['status_code'] == 200) {
        $query = "UPDATE snapshots SET (html, inserted) = ('$source_code', '$now') WHERE pathname = '{$url_path}'";
        $result = pg_query($query) or die('Query failed: ' . pg_last_error());   
    }
})->catch(function ($exception) {
    // inspect the exception here to know what's wrong.
});
;
```

**Comment by Elhellawy** [comment]
the same error Here
and the same environemnt

**Comment by partyka1** [comment]
I'm getting the same error while running Laravel PHPUnit tests on Gitlab CI Docker Runner:
```php
Fatal error: Uncaught Spatie\Async\Output\ParallelError in /var/www/html/vendor/spatie/async/src/Output/ParallelError.php:11
Stack trace:
#0 /var/www/html/vendor/spatie/async/src/Process/ParallelProcess.php(126): Spatie\Async\Output\ParallelError::fromException('')
#1 /var/www/html/vendor/spatie/async/src/Process/ProcessCallbacks.php(51): Spatie\Async\Process\ParallelProcess->resolveErrorOutput()
#2 /var/www/html/vendor/spatie/async/src/Pool.php(197): Spatie\Async\Process\ParallelProcess->triggerError()
#3 /var/www/html/vendor/spatie/async/src/Pool.php(285): Spatie\Async\Pool->markAsFailed(Object(Spatie\Async\Process\ParallelProcess))
#4 /var/www/html/vendor/symfony/process/Process.php(830): Spatie\Async\Pool->Spatie\Async\{closure}(17, Array)
#5 /var/www/html/vendor/symfony/process/Process.php(168): Symfony\Component\Process\Process->stop(0)
#6 [internal function]: Symfony\Component\Process\Process->__destruct()
#7 {main}
  thrown in /var/www/html/vendor/spatie/async/src/Output/ParallelError.php on line 11
ERROR: Job failed: exit code 2
```

**Comment by partyka1** [comment]
Yes, I've added:
```php
$pool->add(function () {
      //....
})->catch(function ($exception) {
      dd($exception);
});
```
and the output is the same:
```php

Spatie\Async\Output\ParallelError {#11113
  #message: ""
  #code: 0
  #file: "/var/www/html/vendor/spatie/async/src/Output/ParallelError.php"
  #line: 11
  trace: {
    /var/www/html/vendor/spatie/async/src/Output/ParallelError.php:11 { …}
    /var/www/html/vendor/spatie/async/src/Process/ParallelProcess.php:126 { …}
    /var/www/html/vendor/spatie/async/src/Process/ProcessCallbacks.php:51 { …}
    /var/www/html/vendor/spatie/async/src/Pool.php:197 { …}
    /var/www/html/vendor/spatie/async/src/Pool.php:285 { …}
    /var/www/html/vendor/symfony/process/Process.php:830 { …}
    /var/www/html/vendor/symfony/process/Process.php:168 { …}
    Symfony\Component\Process\Process->__destruct() {}
  }
}
```

**Comment by brendt** [comment]
Something is going wrong in your sub tasks. You could try to run the child process manually to see what exactly is happening, or read the PHP console error log

**Comment by partyka1** [comment]
I'll try to do this later, I'm using spatie/async only for phpunit tests and the bug is only happening while running CI on Gitlab, manually running the tests on my local docker is fine.

**Comment by partyka1** [comment]
In my case, it helped running `$runnable->stop()` on every started `Runnable` before exit of app.

**Comment by henriquetroiano** [comment]
Did you are awating the pool?

$pool->wait();
