### ISSUE TITLE
 InvalidArgumentException : Unknown setter 'date'

### ISSUE THREAD

**Issue by platformsfx** [spatie/async#45]
Same here:

```
 InvalidArgumentException : Unknown setter 'date'
 at /Users/{PH}/Sites/{PH}/{PH}/vendor/nesbot/carbon/src/Carbon/Carbon.php:1202
 1198| $this->setTimezone($value);
 1199| break;
 1200|
 1201| default:
 1202| throw new InvalidArgumentException(sprintf("Unknown setter '%s'", $name));
 1203| }
 1204| }
 1205|
 1206| /**
```

Exception trace:

1 Carbon\Carbon::__set("date", "2018-10-09 13:30:51.266615")
[internal]:0

2 ReflectionProperty::setValue(Object(Illuminate\Support\Carbon), "2018-10-09 13:30:51.266615")
/Users/{PH}/Sites/{PH}/{PH}/vendor/opis/closure/src/SerializableClosure.php:397

code:
```
    $sPool = SPool::create()->concurrency(20);
    $sPool[] = async(function () use ($msg){
                             // Some process here
                       })->then(function ($output) {
                            // Handle success
                            \Log::info("OUT: " . $output);
                      })->catch(function (\Exception $exception) {
                         // Handle exception
                        \Log::info($exception->getMessage());
                    });
    await($sPool);
```

AND WHILE I used try catch for the SerializableClosure.php:397 I Got this:

[2018-10-09 13:18:29] local.INFO: Unknown setter 'date'
[2018-10-09 13:18:29] local.INFO: Unknown setter 'timezone_type'
[2018-10-09 13:18:29] local.INFO: DateTime::setTimezone(): The DateTime object has not been correctly initialized by its constructor

**Comment by platformsfx** [comment]
#37

**Comment by brendt** [comment]
Hi @platformsfx 

This issue is not very clear. It's very difficult for maintainers to understand unclear issues, this is why I'd like you to ask to read up on our expectations here: https://sebastiandedeyne.com/a-good-issue  

Furthermore, be sure to read the [README](https://github.com/spatie/async/blob/master/README.md) of this package in detail before opening an issue.

As said in #37, and with the information provided: I don't think this is an issue in the package, but rather in the code.

I'm going to close this issue for now, as it isn't clear.

**Comment by platformsfx** [comment]
Hey @brendt 
I'm sorry if I wasn't clear to explain the issue.

* I'm using Laravel 5.7.9 (latest), with php 7.1.11
* I tested if I'm in supported environment using the static method isSupported, AND YES THIS IS A SUPPORTED ENV.
 
I'm using your package to make my code async because of the big data I'm receiving, so I tested it inside a ratchet websocket closure, it dead with below Exception:
```
InvalidArgumentException : Unknown setter 'date'
```
If you need a more trace, this is the trace which may help: 
```
1 Carbon\Carbon::__set("date", "2018-10-09 13:30:51.266615")
[internal]:0

2 ReflectionProperty::setValue(Object(Illuminate\Support\Carbon), "2018-10-09 13:30:51.266615")
/Users/{PH}/Sites/{PH}/{PH}/vendor/opis/closure/src/SerializableClosure.php:397
```

I made a try catch closure to see what happening in SerializableClosure.php:397, So I Got this exceptions: 
```
[2018-10-09 13:18:29] local.INFO: Unknown setter 'date'
[2018-10-09 13:18:29] local.INFO: Unknown setter 'timezone_type'
[2018-10-09 13:18:29] local.INFO: DateTime::setTimezone(): The DateTime object has not been correctly initialized by its constructor
```


Now, I remove the Ratchet wesocket code, I used just your example from the README,
THIS Code below: 
```
$sPool = SPool::create()->concurrency(20);
        $msgs = ['a', 'b', 'c'];
        foreach ($msgs as $msg) {
            
                $sPool[] = async(function () use ($msg) {
                        \Log::info($msg);
                })->then(function ($output) {
                    // Handle success
                    \Log::info("OUT: " . $output);
                })->catch(function (\Exception $exception) {
                    // Handle exception
                     \Log::info($exception->getMessage());
                });
        }

        await($sPool);
```

And I got this Exception: 

```
[2018-10-09 14:15:18] local.INFO: The serialized closure is signed. Make sure you use a security provider for both serialization and unserialization.

#0 [internal function]: Opis\Closure\SerializableClosure->unserialize('@{"closure":"a:...')
#1 /Users/{PH}/Sites/{PH}/{PH}/vendor/opis/closure/functions.php(34): unserialize('C:32:"Opis\\Clos...')
#2 /Users/{PH}/Sites/{PH}/{PH}/vendor/spatie/async/src/Runtime/ParentRuntime.php(92): Opis\Closure\unserialize('C:32:"Opis\\Clos...')
#3 /Users/{PH}/Sites/{PH}/{PH}/vendor/spatie/async/src/Runtime/ChildRuntime.php(23): Spatie\Async\Runtime\ParentRuntime::decodeTask('QzozMjoiT3Bpc1x...')
#4 {main} 
```

Thank you :)

**Comment by platformsfx** [comment]
@brendt I moved to use Task class, and it's working good :) Thank you very much. 👍

**Comment by amitozdeol** [comment]
I'm still having the same problem too, even with or without `Task`
Laravel version - 5.6 

```InvalidArgumentException: Unknown setter 'date' in /Users/{PD}/www/{Proj_name}/vendor/nesbot/carbon/src/Carbon/Carbon.php:1011
Stack trace:
#0 [internal function]: Carbon\Carbon->__set('date', '2018-10-18 15:0...')
#1 /Users/{PD}/www/{Proj_name}/vendor/opis/closure/src/SerializableClosure.php(397): ReflectionProperty->setValue(Object(Illuminate\Support\Carbon), '2018-10-18 15:0...')
#2 /Users/{PD}/www/{Proj_name}/vendor/opis/closure/src/SerializableClosure.php(357): Opis\Closure\SerializableClosure::wrapClosures(Object(Illuminate\Support\Carbon), Object(Opis\Closure\ClosureScope))
#3 /Users/{PD}/www/{Proj_name}/vendor/opis/closure/src/SerializableClosure.php(357): Opis\Closure\SerializableClosure::wrapClosures(Array, Object(Opis\Closure\ClosureScope))
#4 /Users/{PD}/www/{Proj_name}/vendor/opis/closure/src/SerializableClosure.php(395): Opis\Closure\SerializableClosure::wrapClosures(Array, Object(Opis\Closure\ClosureScope))
#5 /Users/{PD}/www/{Proj_name}/vendor/opis/closure/functions.php(19): Opis\Closure\SerializableClosure::wrapClosures(Object(App\Task\Subscriptions))
#6 /Users/{PD}/www/{Proj_name}/vendor/spatie/async/src/Runtime/ParentRuntime.php(87): Opis\Closure\serialize(Object(App\Task\Subscriptions))
#7 /Users/{PD}/www/{Proj_name}/vendor/spatie/async/src/Runtime/ParentRuntime.php(70): Spatie\Async\Runtime\ParentRuntime::encodeTask(Object(App\Task\Subscriptions))
#8 /Users/{PD}/www/{Proj_name}/vendor/spatie/async/src/Pool.php(118): Spatie\Async\Runtime\ParentRuntime::createProcess(Object(App\Task\Subscriptions))
#9 /Users/{PD}/www/{Proj_name}/app/Observers/BuildingGroupManagerObserver.php(61): Spatie\Async\Pool->add(Object(App\Task\Subscriptions))
#10 [internal function]: App\Observers\BuildingGroupManagerObserver->created(Object(App\Models\BuildingGroupManager))
#11 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(379): call_user_func_array(Array, Array)
#12 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(209): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('eloquent.create...', Array)
#13 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(182): Illuminate\Events\Dispatcher->dispatch('eloquent.create...', Array, false)
#14 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php(162): Illuminate\Events\Dispatcher->fire('eloquent.create...', Object(App\Models\BuildingGroupManager))
#15 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(773): Illuminate\Database\Eloquent\Model->fireModelEvent('created', false)
#16 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(615): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#17 /Users/{PD}/www/{Proj_name}/app/Http/Controllers/Access/AccessGroupController.php(244): Illuminate\Database\Eloquent\Model->save()
#18 /Users/{PD}/www/{Proj_name}/app/Http/Controllers/Access/AccessGroupController.php(184): App\Http\Controllers\Access\AccessGroupController->addAllUsers('14', Array)
#19 [internal function]: App\Http\Controllers\Access\AccessGroupController->addUser(Object(App\Http\Requests\AccessValidationRequest))
#20 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#21 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('addUser', Array)
#22 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Access\AccessGroupController), 'addUser')
#23 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\Routing\Route->runController()
#24 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Routing/Router.php(665): Illuminate\Routing\Route->run()
#25 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /Users/{PD}/www/{Proj_name}/app/Http/Controllers/BaseController.php(179): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(133): App\Http\Controllers\BaseController->App\Http\Controllers\{closure}(Object(Illuminate\Http\Request), Object(Closure))
#28 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /Users/{PD}/www/{Proj_name}/app/Http/Middleware/IsLoggedIn.php(40): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): App\Http\Middleware\isLoggedIn->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(67): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#52 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Routing/Router.php(642): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#53 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Routing/Router.php(608): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#54 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Routing/Router.php(597): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#55 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#56 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#57 /Users/{PD}/www/{Proj_name}/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#58 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 /Users/{PD}/www/{Proj_name}/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#61 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#62 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#64 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#65 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#66 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#67 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#68 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#69 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#70 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#71 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#72 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#73 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#74 /Users/{PD}/www/{Proj_name}/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))```

**Comment by brendt** [comment]
@amitozdeol Have you read this? https://github.com/spatie/async/issues/23
